name: neom_generator
description: Neom Generator for Open Neom.
version: 1.4.0-dev
homepage: https://github.com/Open-Neom/neom_generator

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core: ^1.4.1-dev
  neom_commons: ^1.4.1-dev

#  FUTURE EXPERIMENTAL USE:
#  neom_vr:
#    git:
#      url: git@github.com:Cyberneom/neom_vr.git

  sleek_circular_slider: ^2.0.1

  #Audio Processing Experimental
  surround_frequency_generator: ^1.0.0

  #AudioProcessing
  flutter_sound: ^9.28.0
  pitch_detector_dart: ^0.0.7

  #Tonic is a Flutter-compatible Dart package that models components of music theory.
  #Used for Neom Harmony
  #tonic: ^0.2.4

  # TRANSITIVE DEPENDENCIES FOR PUB.DEV PUBLISHING
  cloud_firestore: ^6.0.0
  get: ^5.0.0-release-candidate-9.3.2
  enum_to_string: ^2.2.1
  rflutter_alert: ^2.0.7
  permission_handler: ^12.0.1 # Corrected to the version in the log
  webview_flutter: ^4.13.0
  webview_flutter_platform_interface: ^2.14.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.9.0
  path_provider: ^2.1.5 # Inferred from file system access

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
